[package]
name = "bitbar-mediawiki-watchlist"
version = "0.1.0"
authors = ["Fenhl <fenhl@fenhl.net>"]
edition = "2018"

[[bin]]
name = "bitbar-mediawiki-watchlist"
path = "src/main.rs"
doc = false
test = false
bench = false

[[bin]]
name = "open-all"
path = "src/bin/open_all.rs"
doc = false
test = false
bench = false

[dependencies]
itertools = "*"
serde = "1"
serde_derive = "1"
serde_json = "1"
wikibase = "*"
xdg-basedir = "1"
