[package]
name = "bitbar-mediawiki-watchlist"
version = "0.2.4"
authors = ["Fenhl <fenhl@fenhl.net>"]
edition = "2021"

[[bin]]
name = "bitbar-mediawiki-watchlist"
path = "src/main.rs"

[dependencies]
futures = "0.3"
itertools = "0.10"
maplit = "1"
mediawiki = "0.2"
serde_json = "1"
thiserror = "1"
url = "2"
xdg = "2"

[dependencies.bitbar]
version = "0.8"
features = ["base64"]

[dependencies.reqwest]
version = "0.11"
default-features = false
features = ["rustls-tls", "trust-dns"]

[dependencies.serde]
version = "1"
features = ["derive"]
