[package]
name = "bitbar-mediawiki-watchlist"
version = "0.1.0"
authors = ["Fenhl <fenhl@fenhl.net>"]

[dependencies]
serde = "1.0.33"
serde_derive = "1.0.33"
serde_json = "1.0.11"
#wikibase = "0.1.5" #WAITING FOR https://gitlab.com/tobias47n9e/wikibase_rs/issues/1
xdg-basedir = "1.0.0"

[dependencies.wikibase]
git = "https://gitlab.com/fenhl/wikibase_rs"
branch = "fix-regex"
