[package]
name = "bitbar-mediawiki-watchlist"
version = "0.2.1"
authors = ["Fenhl <fenhl@fenhl.net>"]
edition = "2018"

[[bin]]
name = "bitbar-mediawiki-watchlist"
path = "src/main.rs"
test = false
bench = false

[dependencies]
derive_more = "0.99"
futures = "0.3"
itertools = "0.9"
maplit = "1"
mediawiki = "0.2"
notify-rust = "4"
reqwest = "0.10"
serde_json = "1"
url = "2"
xdg-basedir = "1"

[dependencies.bitbar]
version = "0.3"
features = ["base64"]

[dependencies.serde]
version = "1"
features = ["derive"]

[dependencies.wheel]
git = "https://github.com/fenhl/wheel"
branch = "main" #TODO remove once Cargo has proper support for default branches
